baseurl = "https://nitechcommunity.netlify.com/"
title = "NI Tech Community"
theme = "ghostwriter"
languageCode = "en-gb"
copyright = "NI Tech Community"

[Author]
    name = "NI Tech Community"
    profile = "https://nitechcommunity.co.uk/"

[Params]
    intro = true
    headline = ""
    description = ""
    github = "https://github.com/nitechcommunity"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    exponeaJsUrl = ""
    exponeaTarget = ""
    exponeaToken = ""
    exponeaTrackVisits = false
    readingTime = true
    readingTimeText = "Estimated reading time:"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Slack"
    url = "/page/slack/"
    weight = 1

[[menu.main]]
    name = "Conferences"
    url = "/page/conference/"
    weight = 2

[[menu.main]]
    name = "User groups"
    url = "/page/user_groups/"
    weight = 3

[[menu.main]]
    name = "Code of conduct"
    url = "/page/code_of_conduct/"
    weight = 4
